### ISSUE TITLE
[  script:npwd_crypto] [npwd_crypto] ERROR: No framework detected

### ISSUE THREAD

**Issue by operationairstrike** [npwd-community/npwd_crypto#16]
I use esx legacy wiht ox inventory, what am i doing wrong?

this is my config:

{
  "maxHistory": 10,
  "logging": {
    "enabled": false,
    "webhook": ""
  },
  "tick": {
    "min": 15,
    "max": 250,
    "upDownRatio": 0.6,
    "maxDeviation": 10,
    "interval": 15,
    "crashChance": 0.05
  }
}

**Comment by LiamDormon** [comment]
It's not detecting a framework probably because you renamed your resources to something stupid. And please, don't use this resource unless you want your server economy ruined.

**Comment by operationairstrike** [comment]
No npwd and npwd_crypto aren't renamed es_extended aswell unchanged. What are the depencies that have to have a certain name?
