### ISSUE TITLE
BUG: Application can't be loaded

### ISSUE THREAD

**Issue by 123B3n** [npwd-community/npwd_crypto#3]
It's impossible to load the application, I've tried loading it after `npwd` and before, I 've even started it before anything else. Each time I get this code.

```
Failed to load external app "npwd_crypto". Make sure it is started before NPWD. (webpack-internal:///69747:13109)
[object Event] (webpack-internal:///69747:13110)
```

I've tried rebuilding it myself, but same there nothing changes.

**Comment by CarlBishop** [comment]
Can you explain how did you fixed this?
I'm facing the same issue

**Comment by LiamDormon** [comment]
Compile the app

**Comment by 123B3n** [comment]
> Can you explain how did you fixed this? I'm facing the same issue

Pretty sure I just added the HTML files into a dist folder under web since if I'm not mistaken their not in the dist folder in there which causes the phone to not load the files properly. Don't quote me on that, been a few days ago I fixed it so I'm not 100% sure, but I remember it was something like that or possible in another app.
