### ISSUE TITLE
Cannot read property toString of null

### ISSUE THREAD

**Issue by mikigoalie** [npwd-community/npwd_crypto#4]
Hello, keep getting this error on latest crypto & esx as well as latest npwd built (both scripts are built, not releases, but happens with release too). Didn't happen before I updated to latest esx I believe (few commits before rounding for each currency)

image preview of the error

![image](https://user-images.githubusercontent.com/22800996/188854470-da1b1efc-42e3-4089-bdf6-4724fd0f11c0.png)

**Comment by LiamDormon** [comment]
Repro?

**Comment by mikigoalie** [comment]
Create new char, open app, crashes. 

BalanceList.tsx 19 >        text={balance.toString()} seems to be null although I have added crypto to the config of esx

**Comment by LiamDormon** [comment]
Investigating this, seems like ESX broke something on their end

**Comment by LiamDormon** [comment]
Fixed with latest release of es_extended
