### ISSUE TITLE
Feature Request: Close dialogues on submit

### ISSUE THREAD

**Issue by TonybynMp4** [npwd-community/npwd_crypto#5]
When clicking on the confirm button it doesn't close the smol input page and i think it probably should tbh

**Comment by LiamDormon** [comment]
It isn't supposed to be closing, would you like to change this to a feature request

**Comment by TonybynMp4** [comment]
> It isn't supposed to be closing, would you like to change this to a feature request

Oh well then yeah sure
Thought it was a bug cauz you'd kinda expect it to close lol

**Comment by Khatrie** [comment]
Agreed on this one, thought it was a bug myself.

**Comment by IamLation** [comment]
I also thought this was a bug hahah - would love to see this implemented
