### ISSUE TITLE
[BUG?] ESX Crypto displaying rounded balance?

### ISSUE THREAD

**Issue by mikigoalie** [npwd-community/npwd_crypto#6]
Hello, I'm not sure if it's intended, but crypto is always showing rounded number and never float. Is it intentional? Screens below, I think they're self-explainatory
![image](https://user-images.githubusercontent.com/22800996/189073237-d0c26996-d885-4ff8-9814-59a42a7ab2ce.png)
![image](https://user-images.githubusercontent.com/22800996/189073301-8801be95-bf39-445b-b8c8-4e3d748bda97.png)

**Comment by LiamDormon** [comment]
This is known, was an error on ESX's end and theres a patch for it
